In [2]:
import numpy as np
arr = np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90], [100, 110, 120]])
print(arr)

[[ 10  20  30]
 [ 40  50  60]
 [ 70  80  90]
 [100 110 120]]


In [23]:
arr[arr[:, 0] == 70]

array([[70, 80, 90]])